const GIFS = {
  LOAD: "GIFS_LOAD",
  SEARCH: "GIFS_SEARCH",
  LOAD_SUCCESS: "GIFS_LOAD_SUCCESS",
  LOAD_FAIL: "GIFS_LOAD_FAIL"
};

const TRENDINGS = {
  LOAD: "TRENDINGS_LOAD",
  LOAD_SUCCESS: "TRENDINGS_LOAD_SUCCESS",
  LOAD_FAIL: "TRENDINGS_LOAD_FAIL"
};

const SEARCHTERM = {
  UPDATE: "SEARCHTERM_UPDATE"
};

export { GIFS, TRENDINGS, SEARCHTERM };
